### ISSUE TITLE
[TODO] Fix: lights may turn on if they are already off

### ISSUE THREAD

**Issue by Moyster** [mpolednik/script.kodi.hue.ambilight#24]
Fix: lights may turn on if they are already off, need better state checking

**Comment by tremby** [comment]
Yes please. I was about to post the same thing.

Perhaps probe the lights every minute or so while not playing a video for their state, and restore to whatever the last one was before the video was started, rather than what I assume you're doing at the moment which is to just probe them once when the script is started.

Or you could perhaps probe for state as the video starts playing, just before telling the lights to dim/switch off.

**Comment by mpolednik** [comment]
I'm not too happy about polling the lights with set interval, but the second suggestion sounds perfect. I'll see if it could fit refactoring-v9-candidate branch.
